// Gallery images (SPEC.md §5, §10). Currently local abstract placeholders
// generated by scripts/generate-placeholders.mjs — swap files + ids here when
// the real §10 image set is produced; components don't change. Alt text
// lives in /messages under gallery.images.<id>.alt.

export interface GalleryImage {
  /** Key into gallery.images.* in /messages */
  id: string;
  src: string;
  width: number;
  height: number;
}

// Aspect ratios alternate 4:5 / 1:1 / 3:4 for masonry rhythm (§10).
export const GALLERY_IMAGES: readonly GalleryImage[] = [
  { id: "g1", src: "/images/gallery-01.svg", width: 800, height: 1000 },
  { id: "g2", src: "/images/gallery-02.svg", width: 900, height: 900 },
  { id: "g3", src: "/images/gallery-03.svg", width: 750, height: 1000 },
  { id: "g4", src: "/images/gallery-04.svg", width: 800, height: 1000 },
  { id: "g5", src: "/images/gallery-05.svg", width: 900, height: 900 },
  { id: "g6", src: "/images/gallery-06.svg", width: 750, height: 1000 },
  { id: "g7", src: "/images/gallery-07.svg", width: 800, height: 1000 },
  { id: "g8", src: "/images/gallery-08.svg", width: 900, height: 900 },
  { id: "g9", src: "/images/gallery-09.svg", width: 750, height: 1000 },
] as const;
