// Gallery images (SPEC.md §5, §10). Currently local abstract placeholders
// generated by scripts/generate-placeholders.mjs — swap src/alt here when
// the real §10 image set is produced; components don't change.

export interface GalleryImage {
  src: string;
  alt: string;
  width: number;
  height: number;
}

// Aspect ratios alternate 4:5 / 1:1 / 3:4 for masonry rhythm (§10).
export const GALLERY_IMAGES: readonly GalleryImage[] = [
  { src: "/images/gallery-01.svg", alt: "Placeholder artwork — morning light study in cream and caramel", width: 800, height: 1000 },
  { src: "/images/gallery-02.svg", alt: "Placeholder artwork — beans and warm tones", width: 900, height: 900 },
  { src: "/images/gallery-03.svg", alt: "Placeholder artwork — pour-over abstraction", width: 750, height: 1000 },
  { src: "/images/gallery-04.svg", alt: "Placeholder artwork — pastry case shapes", width: 800, height: 1000 },
  { src: "/images/gallery-05.svg", alt: "Placeholder artwork — hands and cup composition", width: 900, height: 900 },
  { src: "/images/gallery-06.svg", alt: "Placeholder artwork — laptop corner geometry", width: 750, height: 1000 },
  { src: "/images/gallery-07.svg", alt: "Placeholder artwork — plants by the window", width: 800, height: 1000 },
  { src: "/images/gallery-08.svg", alt: "Placeholder artwork — wood grain textures", width: 900, height: 900 },
  { src: "/images/gallery-09.svg", alt: "Placeholder artwork — espresso still life", width: 750, height: 1000 },
] as const;
